---

- name: Install and Start the Ngnix
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt: 
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
